#name: Release
#
#on:
#  push:
#    branches:
#      - main
#
#concurrency: ${{ github.workflow }}-${{ github.ref }}
#
#jobs:
#  release:
#    name: Release
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Repo â¬‡ï¸
#        uses: actions/checkout@v3
#
#      - name: Setup Node.js ğŸŒ
#        uses: actions/setup-node@v3
#        with:
#          node-version: 17
#          cache: 'pnpm'
#
#      - name: Install dependency ğŸ’»
#        run: pnpm install --frozen-lockfile --ignore-scrips
#
#      - name: Create Release Pull Request ğŸ’¥
#        uses: changesets/action@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
